// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gnzocasyggbbtcnullyz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imduem9jYXN5Z2diYnRjbnVsbHl6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ5MTM5ODEsImV4cCI6MjA3MDQ4OTk4MX0.AZBCZJF8pp9Wnsfj01fb6GQyaIbktr8BdPWUXvt9wDo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});